databases:
  - name: access_watch_db
    plan: free
    databaseName: access_watch
    user: access_watch

services:
  - type: web
    plan: free
    name: access_watch
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn access_watch.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: access_watch_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
